# Generated by Django 3.0.8 on 2020-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='case',
            name='box_item',
            field=models.ManyToManyField(to='index.item'),
        ),
    ]
